version: '3'

services:
  ssl-ca:
    image: ubuntu:18.04
    restart: always
    container_name: ssl-ca
    hostname: ssl-ca01
    domainname: inahym.com
    tty: true

networks:
  default:
    external:
      name: common
