version: '3'

services:
  ldap-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ldap-server
    hostname: ldap01
    domainname: inahym.com
    environment:
      LDAP_ORGANISATION: inahym Inc.
      LDAP_DOMAIN: inahym.com
      LDAP_ADMIN_PASSWORD: admin
    volumes: 
       - '/srv/ldap/data:/var/lib/ldap'
       - '/srv/ldap/config:/etc/ldap/slapd.d'
    tty: true

  ldap-admin:
    image: osixia/phpldapadmin:stable-amd64
    restart: always
    container_name: ldap-admin
    hostname: ldap-admin01
    domainname: inahym.com
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"

networks:
  default:
    external:
      name: common
