---
# tasks file for ldap-search

- name: ldap-search
  community.general.ldap_search:
    dn: "dc=ldap,dc=inahym,dc=com"
    scope: children
    bind_dn: "{{ ldap_auth.bind_dn }}"
    bind_pw: "{{ ldap_auth.bind_pw }}"
  register: ret

- name: debug
  debug: var=ret
