---
# tasks file for update-ca-cert

- name: Generate openssl CA private key
  community.crypto.openssl_privatekey:
    path: "{{ ca.dirname }}/{{ ca.key.name }}"

- name: Generate openssl certificate signing request
  community.crypto.openssl_csr:
    privatekey_path: "{{ ca.dirname }}/{{ ca.key.name }}"
    path: "{{ ca.dirname }}/{{ ca.csr.name }}"
    common_name: "{{ ca.csr.common_name }}"
    country_name: "{{ ca.csr.country_name }}"
    organization_name: "{{ ca.csr.organization_name }}"
    email_address: "{{ ca.csr.email_address }}"
    subject_alt_name: "{{ ca.csr.subject_alt_name }}"

- name: Generate a self-signed openssl certificate
  community.crypto.x509_certificate:
    privatekey_path: "{{ ca.dirname }}/{{ ca.key.name }}"
    path: "{{ ca.dirname }}/{{ ca.crt.name }}"
    csr_path: "{{ ca.dirname }}/{{ ca.csr.name }}"
    provider: selfsigned
