---
# tasks file for enroll-ldap
- name: Enroll OU
  community.general.ldap_entry:
    dn: "ou={{ item.rdn }},{{ base_dn }}"
    objectClass: organizationalUnit
  loop: "{{ ou_list }}"

- name: Enroll CN under OU
  community.general.ldap_entry:
    dn: "cn={{ item.1.cn }},ou={{ item.0.rdn }},{{ base_dn }}"
    objectClass: "{{ item.0.objectClass }}"
    attributes: "{{ item.1 }}"
  with_subelements: 
    - "{{ ou_list }}"
    - attr  

- name: register password
  shell: "cat {{ cred_key }}"
  register: row_pass
  delegate_to: localhost

- name: command slappasswd
  shell: "slappasswd -s {{ row_pass.stdout }}"
  register: key

- name: Change ansible password for ldap
  community.general.ldap_attrs:
    dn: "cn=ansible,ou=users,{{ base_dn }}"
    attributes:
      userPassword: "{{ key.stdout }}"
    state: exact
