---
# tasks file for enroll-cert

- name: Generate openssl CA private key
  community.crypto.openssl_privatekey:
    path: "{{ ca.dirname }}/{{ ca.key.name }}"

- name: Generate openssl certificate signing request
  community.crypto.openssl_csr:
    privatekey_path: "{{ ca.dirname }}/{{ ca.key.name }}"
    path: "{{ ca.dirname }}/{{ ca.csr.name }}"
    common_name: "{{ update_ca_cert_csr.common_name }}"
    country_name: "{{ update_ca_cert_csr.country_name }}"
    organization_name: "{{  update_ca_cert_csr.organization_name }}"
    email_address: "{{ update_ca_cert_csr.email_address }}"
    subject_alt_name: "{{ update_ca_cert_csr.subject_alt_name }}"

- name: Generate a self-signed openssl certificate
  community.crypto.x509_certificate:
    privatekey_path: "{{ ca.dirname }}/{{ ca.key.name }}"
    path: "{{ ca.dirname }}/{{ ca.crt.name }}"
    csr_path: "{{ ca.dirname }}/{{ ca.csr.name }}"
    provider: selfsigned
